# application: kykamath-hw
# application: social-media-spread
application: social-trails
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /.*
  script: requests.py